# Generated by Django 4.2.7 on 2023-11-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='adi')),
                ('age', models.IntegerField(verbose_name='yashi')),
            ],
            options={
                'verbose_name': 'musteri',
                'verbose_name_plural': 'musteriler',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GYM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='adi')),
                ('adress', models.TextField(verbose_name='adress')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'adlari',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='adi')),
                ('specialization', models.CharField(max_length=255, verbose_name='peshesi')),
                ('gym', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.gym')),
            ],
            options={
                'verbose_name': 'mesqci',
                'verbose_name_plural': 'mesqciler',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tarix')),
                ('duration', models.IntegerField(verbose_name='say')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.client')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.trainer')),
            ],
            options={
                'verbose_name': 'musteri',
                'verbose_name_plural': 'musteriler',
                'ordering': ('client',),
            },
        ),
    ]
