# Generated by Django 4.2.5 on 2023-11-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ('client',), 'verbose_name': 'mesq vaxti', 'verbose_name_plural': 'mesq vaxtlari'},
        ),
    ]
